-- Seed data matching src/lib/mock-data.ts

INSERT INTO public.servicios (id, name_es, name_en, description_es, description_en, "order") VALUES
  ('ecommerce', 'Quiero vender mis productos por internet', 'I want to sell my products online', 'Tienda online completa: catálogo, carrito, pagos y panel para que manejes tus productos tú mismo.', 'Full online store: catalog, cart, payments and a panel so you manage your own products.', 1),
  ('seo-web', 'Quiero que mi negocio aparezca en Google y lo encuentren', 'I want my business to show up on Google', 'Página profesional optimizada para que tus clientes te encuentren cuando busquen lo que ofreces.', 'Professional page optimized so your customers find you when they search for what you offer.', 2),
  ('portfolio', 'Quiero mostrar mi trabajo o mi carrera', 'I want to showcase my work or career', 'Portafolio o CV digital que transmite quién eres y qué has logrado, de forma profesional.', 'Portfolio or digital resume that shows who you are and what you have achieved, professionally.', 3),
  ('landing', 'Quiero promocionar algo puntual', 'I want to promote something specific', 'Landing page enfocada en convertir visitantes en clientes para un producto, servicio o evento.', 'Landing page focused on converting visitors into customers for a product, service, or event.', 4),
  ('custom', 'No estoy seguro / quiero que me asesores', 'I''m not sure / I''d like some advice', 'Cuéntame tu idea y te oriento hacia la solución más adecuada para tu negocio.', 'Tell me your idea and I''ll guide you toward the best solution for your business.', 5)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.proyectos (slug, category, service_id, featured, business_es, business_en, problem_es, problem_en, solution_es, solution_en, technologies, live_url) VALUES
  ('tienda-artesanias-quito', 'demo', 'ecommerce', true, 'Artesanías del Ecuador', 'Ecuador Crafts', 'Un taller artesanal en Quito vendía solo por Instagram, perdiendo clientes que no usaban redes sociales.', 'An artisan workshop in Quito was selling only through Instagram, missing customers who don''t use social media.', 'Le hice una tienda online donde los clientes pueden ver el catálogo completo, pagar con tarjeta y el dueño maneja su inventario sin depender de nadie.', 'I built them an online store where customers can browse the full catalog, pay by card, and the owner manages their inventory independently.', ARRAY['Next.js', 'Supabase', 'Stripe', 'TypeScript'], NULL),
  ('restaurante-la-ronda', 'demo', 'seo-web', true, 'Restaurante La Ronda', 'La Ronda Restaurant', 'Un restaurante del centro histórico no aparecía en Google y sus clientes llegaban solo por recomendación boca a boca.', 'A historic center restaurant wasn''t showing up on Google and customers only found it through word of mouth.', 'Le construí una página optimizada para buscadores con menú, fotos, ubicación y reseñas. En tres meses empezó a aparecer en los primeros resultados locales.', 'I built them a search-optimized page with menu, photos, location and reviews. Within three months it started appearing in top local results.', ARRAY['Next.js', 'Tailwind CSS', 'TypeScript'], NULL),
  ('portafolio-fotografa', 'demo', 'portfolio', true, 'Daniela López — Fotógrafa', 'Daniela López — Photographer', 'Una fotógrafa profesional compartía su trabajo solo en Instagram, sin poder presentar un portafolio profesional a clientes corporativos.', 'A professional photographer was sharing work only on Instagram, unable to present a professional portfolio to corporate clients.', 'Le diseñé un portafolio visual con galerías por categoría, página de contacto y carga ultra-rápida de imágenes para que nunca pierda a un cliente por lentitud.', 'I designed a visual portfolio with galleries by category, a contact page and ultra-fast image loading so she never loses a client due to slow load times.', ARRAY['Next.js', 'Framer Motion', 'Supabase Storage'], NULL),
  ('landing-curso-online', 'demo', 'landing', false, 'Curso de Finanzas Personales', 'Personal Finance Course', 'Un coach financiero lanzaba un curso pero no tenía una página convincente para convertir interesados en compradores.', 'A financial coach was launching a course but had no convincing page to convert interested people into buyers.', 'Le hice una landing page con testimonios, módulos del curso, contador de plazas y botón de compra directo. Vendió el 80% de cupos en la primera semana.', 'I built a landing page with testimonials, course modules, a seat counter and a direct purchase button. They sold 80% of spots in the first week.', ARRAY['Next.js', 'Tailwind CSS', 'Stripe'], NULL),
  ('app-gestion-inventarios', 'cliente', 'custom', false, 'Distribuidora El Sol', 'El Sol Distributors', 'Una distribuidora local manejaba su inventario en hojas de cálculo, perdiendo el rastro de productos y generando pedidos duplicados a proveedores.', 'A local distributor was managing inventory in spreadsheets, losing track of products and generating duplicate supplier orders.', 'Les desarrollé una app web a medida con panel de control, alertas de stock bajo y generación automática de órdenes de compra. Redujeron errores en un 90%.', 'I built a custom web app with a dashboard, low-stock alerts and automatic purchase order generation. They reduced errors by 90%.', ARRAY['React', 'Node.js', 'PostgreSQL', 'Tailwind CSS'], NULL),
  ('sitio-corredora-propiedades', 'cliente', 'seo-web', false, 'Corredora de Propiedades MG', 'MG Real Estate', 'Una corredora de propiedades tenía un sitio web desactualizado que no aparecía en Google y no generaba leads.', 'A real estate agent had an outdated website that didn''t appear on Google and generated no leads.', 'Le rediseñé el sitio con listado de propiedades, filtros por zona/precio, formulario de contacto integrado y SEO completo. En 2 meses triplicó las consultas.', 'I redesigned their site with property listings, filters by area/price, an integrated contact form and full SEO. Within 2 months inquiries tripled.', ARRAY['Next.js', 'Tailwind CSS', 'TypeScript', 'Supabase'], 'https://mg-propiedades.example.com'),
  ('landing-evento-tech', 'demo', 'landing', false, 'Conferencia TechQuito 2025', 'TechQuito 2025 Conference', 'La organización de una conferencia tech necesitaba una landing para registrar asistentes y patrocinadores en menos de dos semanas.', 'A tech conference organization needed a landing page to register attendees and sponsors in under two weeks.', 'Construí una landing con contador regresivo, formulario de registro, grid de speakers y pasarela de pago. Registraron 300+ asistentes en 10 días.', 'I built a landing page with a countdown timer, registration form, speaker grid and payment gateway. They registered 300+ attendees in 10 days.', ARRAY['Next.js', 'Stripe', 'Tailwind CSS', 'TypeScript'], NULL)
ON CONFLICT (slug) DO NOTHING;
